In [1]:
# Required imports

import pandas as pd

In [4]:
df = pd.read_csv('/Users/akash/Desktop/Terraforming Mars Project/Atmosphere_Data.csv').iloc[:50000,1:]

In [5]:
df = df.drop(['min_temp', 'max_temp', 'pressure', 'avg_temp', 'transformer', 'transformed_min_temp', 'transformed_max_temp', 'transformed_min_temp_dampened', 'transformed_max_temp_dampened', 'transformer_pressure'], axis = 1)

In [6]:
df.columns = ['ls', 'sol', 'target_temp', 'target_pressure']

In [7]:
import numpy as np
import random

df['activity'] = np.nan
df['activity'] = df.activity.apply(lambda x: random.choice(['Nuclear Bomb Seed', 'Radiation Cleaning', 'CO2 Pump', 'BioEngineered O2 Seed', 'Solar Focus', 'Launch Probe']) )

df['activity_type'] = np.nan
df['activity_type'] = df.activity.apply(lambda x: random.choice(['Level 1', 'Level 2', 'Level 3']) )

df['activity_handler'] = np.nan
df['activity_handler'] = df.activity.apply(lambda x: random.choice(['United Nations', 'ISRO', 'NASA', 'ESDA']) )

In [8]:
df['earth_date'] = pd.date_range(start='1/1/2030', periods=len(df), freq='D')

In [9]:
df['trigger_schedule_time'] = np.nan
df['trigger_schedule_time'] = df.trigger_schedule_time.apply(lambda x: random.choice(['12 AM', '12 PM']) ) 

df['mars_satellite_processing_delay_mins'] = np.nan
df['mars_satellite_processing_delay_mins'] = df.mars_satellite_processing_delay_mins.apply(lambda x: random.choice(range(0,10,1)))

In [10]:
df.head(20)

,ls,sol,target_temp,target_pressure,activity,activity_type,activity_handler,earth_date,trigger_schedule_time,mars_satellite_processing_delay_mins
0,155,1,-44.260000,838.520000,CO2 Pump,Level 3,ESDA,2030-01-01,12 PM,7
1,155,2,-45.498114,739.097621,Launch Probe,Level 2,ISRO,2030-01-02,12 PM,4
2,156,3,-43.498041,740.198107,Solar Focus,Level 3,NASA,2030-01-03,12 AM,1
3,156,4,-46.997969,741.298594,Solar Focus,Level 3,ESDA,2030-01-04,12 AM,9
4,157,5,-44.497897,732.399080,BioEngineered O2 Seed,Level 3,ESDA,2030-01-05,12 AM,1
5,157,6,-44.997825,740.499567,BioEngineered O2 Seed,Level 2,ESDA,2030-01-06,12 PM,6
6,158,7,-46.497752,740.600054,Solar Focus,Level 1,NASA,2030-01-07,12 PM,3
7,158,8,-38.497680,740.700540,Solar Focus,Level 2,ISRO,2030-01-08,12 AM,9
8,159,9,-39.997608,742.801027,BioEngineered O2 Seed,Level 1,ESDA,2030-01-09,12 PM,1
9,160,10,-44.259350,839.424379,Nuclear Bomb Seed,Level 3,ESDA,2030-01-10,12 PM,5
10,160,11,-44.259277,839.524866,Solar Focus,Level 2,United Nations,2030-01-11,12 PM,2
11,161,12,-44.259205,839.625352,Solar Focus,Level 2,NASA,2030-01-12,12 PM,0
12,161,13,-38.497319,742.202973,Solar Focus,Level 3,NASA,2030-01-13,12 PM,0
13,162,14,-39.997247,743.303460,CO2 Pump,Level 3,United Nations,2030-01-14,12 AM,0
14,162,15,-45.497174,742.403946,Nuclear Bomb Seed,Level 1,ESDA,2030-01-15,12 PM,4
15,163,16,-40.997102,743.504433,Radiation Cleaning,Level 3,ISRO,2030-01-16,12 AM,0
16,163,17,-42.997030,744.604919,Solar Focus,Level 1,ISRO,2030-01-17,12 PM,7
17,164,18,-44.996958,746.705406,BioEngineered O2 Seed,Level 1,United Nations,2030-01-18,12 PM,7
18,164,19,-44.996885,744.805893,Nuclear Bomb Seed,Level 3,NASA,2030-01-19,12 PM,1
19,165,20,-44.996813,746.906379,Radiation Cleaning,Level 3,United Nations,2030-01-20,12 PM,4

In [11]:
locations = ['Columbia Hills, Gusev', 'Eberswalde',
'Holden Crater',
'Jezero Crater',
'Mawrth Vallis',
'NE Syrtis',
'Nili Fossae',
'SW Melas']

In [12]:
df['martian_activity_location'] = np.nan
df['martian_activity_location'] = df.martian_activity_location.apply(lambda x: random.choice(locations))

In [14]:
df.head().to_csv('Activity.csv')

In [15]:
df.to_json('Activity Data.json',orient='records')